### ISSUE TITLE
Menu always opened

### ISSUE THREAD

**Issue by marieve** [themeselection/sneat-bootstrap-html-admin-template-free#16]
Is there a way to always see the open menu and never show the burger menu?

Thanks!

**Comment by poojadosad** [comment]
Hi [marieve](https://github.com/marieve),

Thanks for getting in touch with us : )

We don't have a burger menu in the free version. If you are using the pro version, Please raise your issue from there.

Pro Version has this feature, link to the demo here: https://demos.themeselection.com/sneat-bootstrap-html-admin-template/html/vertical-menu-template/

Let us know if you have further queries.

**Comment by marieve** [comment]
Hi poojadosad,

I have the free version and there is a burger menu in mobile.

I found a way (in CSS) to keep the menu always opened regardless the resolution. It's not perfect but it works for now.

Thanks for your time.
