### ISSUE TITLE
Colours, config.js

### ISSUE THREAD

**Issue by 5c0tch** [themeselection/sneat-bootstrap-html-admin-template-free#18]
Hello,

This might be a trivial thing to do, but I’m relatively new to bootstrap et al and I have tried checking the documentations/FAQ but am still stuck 2.5 hours later.

I am trying to use ../assets/js/config.js to change the theme colours.

In that file I have

 ```
 colors: {
    primary: '#181818',
    secondary: '#3f6d0a’, …
```

And in my html I have:

 ```
<div class="row" style="margin-bottom:20px;">
                <div class="col-md">
                  <div class="card text-white bg-primary">
                    <div class="card-header">Introduction</div>
                    <div class="card-body”>
```

Yet the colour of that element is still showing as the default #696cff

I believe I have the config.js correctly set up because toggling displayCustomizer turns the customiser on/off.

Thanks for your help

**Comment by 5c0tch** [comment]
I used your Raise Support form and it ended up in a 404 on GitHub.

**Comment by monab** [comment]
Hi @5c0tch,

Thanks for getting in touch with us!!
As we have checked that you have created support in the Sneat PRO version as well, and we have answered there.

So let me know if you have any free template related concern :)
Awaiting to hear from you.

Stay Safe!!
