### ISSUE TITLE
Large Screen Breakpoint

### ISSUE THREAD

**Issue by branforge** [themeselection/sneat-bootstrap-html-admin-template-free#20]
### What problem does this feature solve?

I wanted to change the Large screen break point from 1200px to 1420px. My primary intention is to make the side menu closed until the resolution is 1420px. I have tried changing it in helper.js but does not work. Could you please help me out on this? 

### What does the proposed solution look like?

Menu should be stay collapsed until 1420px screen resolution.

**Comment by SHVM-09** [comment]
Hello @branforge ,

Thank you for using our template and staying in touch with us.

In our latest release **v1.1.0** , we have made menu customisable such that it could be collapsed at any desired breakpoint.

Therefore, download latest free template from here - [v1.1.0](https://github.com/themeselection/sneat-bootstrap-html-admin-template-free/releases/tag/v1.1.0)  and follow the given instructions in [documentation](https://demos.themeselection.com/sneat-bootstrap-html-admin-template/documentation/faq.html#adjust-collapse-breakpoint) for implementing it!

Also, if you require further customisations then you can checkout the Sneat HTML Bootstrap Pro template at [Sneat-Pro-ThemeSelection](https://themeselection.com/item/sneat-bootstrap-html-admin-template/).

Regards!
