### ISSUE TITLE
Bootstrap 5.3 support

### ISSUE THREAD

**Issue by casually-creative** [themeselection/sneat-bootstrap-html-admin-template-free#22]
### What problem does this feature solve?

Being able to use bootstrap 5.3 features.

### What does the proposed solution look like?

A sneat integration built on bootstrap 5.3.

**Comment by casually-creative** [comment]
FYI: I picked "feature request" as issue type, but it got processed as "support".

**Comment by ajaypatelaj** [comment]
@casually-creative Thanks for using our template and sharing your feedback.
We will be upgrading the free version with all the libs soon.

**Comment by casually-creative** [comment]
Thanks for the info!
