### ISSUE TITLE
cannot purchase: signup is broken

### ISSUE THREAD

**Issue by aep** [themeselection/sneat-bootstrap-html-admin-template-free#24]
### Steps to reproduce

Hi, i tried to buy this theme, but the sign up is broken.
it does an ajax request to "https://themeselection.com/wp-admin/admin-ajax.php" which returns 403

**Comment by ajaypatelaj** [comment]
Hello @aep ,

Thanks for raising this issue and helping us. 
We've resolved this and the Authentication flow seems working fine for us. 

Please confirm on your end if you face any challenges.

Thanks & Regards,
Ajay Patel
