### ISSUE TITLE
Heatmap chart responsive problem

### ISSUE THREAD

**Issue by intelryzen** [themeselection/sneat-bootstrap-html-admin-template-free#25]
### Steps to reproduce

I used the sample code as is.

## Mac Chrome
<img width="497" alt="스크린샷 2023-07-20 오후 1 46 15" src="https://github.com/themeselection/sneat-bootstrap-html-admin-template-free/assets/66426612/9424e00e-9ea6-4dd1-b775-8db18524e02e">

## Mobile:
![IMG_5296](https://github.com/themeselection/sneat-bootstrap-html-admin-template-free/assets/66426612/2b18d255-f2b3-47f1-959a-f40eb338215b)

### What is expected?

I expect widgets to scale responsively.

### What is actually happening?

hello.
I am using your product well.

Currently, there is an issue with heatmap chart appearing cropped on devices with small screen sizes. This issue is mainly observed on smaller screens such as mobile or reducing the screen size itself. Particularly, the placement of widgets is skewed on mobile screens as the attached picture.

Can you tell me what should I do to fix this issue?

**Comment by poojadosad** [comment]
Hi @intelryzen,

We have addressed your query in the pro version repository. You can find the response at this link: https://github.com/themeselection/sneat-bootstrap-html-admin-template/issues/83.

As your query has been resolved. We are closing this ticket
If you have any more questions or need further assistance, please feel free to reach out.

Thank you for your support and understanding :)

**Comment by poojadosad** [comment]
Hi @intelryzen,

We have addressed your query in the pro version repository. You can find the response at this link: https://github.com/themeselection/sneat-bootstrap-html-admin-template/issues/83

As your query has been resolved. We are closing this ticket
If you have any more questions or need further assistance, please feel free to reach out.

Thank you for your support and understanding :)
