### ISSUE TITLE
Multisleect is not working

### ISSUE THREAD

**Issue by Abel-Padilla** [themeselection/sneat-bootstrap-html-admin-template-free#27]
### Steps to reproduce

1) Go to Form section
2) scroll down to select section
![image](https://github.com/themeselection/sneat-bootstrap-html-admin-template-free/assets/65582058/878a1389-ab83-4f66-ba30-c5cac02f0725)

### What is expected?

Is expected to be able to select multiple options in the form

### What is actually happening?

Can't select several options

**Comment by SHVM-09** [comment]
Hi [Abel-Padilla](https://github.com/Abel-Padilla),

Thank you for choosing our template and reaching out!

Concerning the multi-select issue you've encountered, it appears you might be using a direct click, whereas for our template, you'll need to utilize the key `shift + click` to select multiple items or `ctrl/cmd + click` to choose alternate items. This behavior aligns with the default settings in Bootstrap, which we've integrated into our template. You can delve into the details [here](https://getbootstrap.com/docs/5.3/forms/select/#sizing).

Should you have any additional questions or need further assistance, feel free to let us know.

Best regards,
