### ISSUE TITLE
JS not Working while integrating html bootstrap 5 free version to Vue Js or React js

### ISSUE THREAD

**Issue by mianmohsin188** [themeselection/sneat-bootstrap-html-admin-template-free#33]
### Steps to reproduce

i have implemented free version of [sneat-bootstrap-html-admin-template-free] to vue js i have imported all files css or js provided in themes found in htm folder suppose i have implemented dashboard content in my react or vue components with vite and npm. I have also installed gulp and npm package as guided in documentation 
**main.js (React)**
import React from 'react'
import ReactDOM from 'react-dom/client'
import { Provider } from 'react-redux';
import { configureStore } from '@reduxjs/toolkit';
import authReducer from './store/auth/authSlice.jsx';
import App from './App.jsx'

import "./assets/vendor/fonts/boxicons.css"
import "./assets/css/demo.css"
import "./assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css"
import "./assets/vendor/css/pages/page-auth.css"
import "./assets/vendor/libs/apex-charts/apex-charts.css"
import "./assets/vendor/js/helpers.js"
import "./assets/js/config.js"

import "./assets/vendor/libs/jquery/jquery.js"
import "./assets/vendor/libs/popper/popper.js"
import "./assets/vendor/js/bootstrap.js"
import "./assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"
import "./assets/vendor/js/menu.js"
import "./assets/vendor/libs/apex-charts/apexcharts.js"
import "./assets/js/main.js"
 import "./assets/js/dashboards-analytics.js"

import './index.css'
const store = configureStore({
    reducer: {
        auth: authReducer,
    },
});

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
      <Provider store={store}>
          <App />
      </Provider>
  </React.StrictMode>,
)
![image](https://github.com/themeselection/sneat-bootstrap-html-admin-template-free/assets/20639671/ba77de6b-6f04-4422-a1a0-6d676d908850)
unable to get password to text when click when no js is loaded as per my observations
so as when i logged in dashboard sidebar menus dropdown ist are not expanding further more charts are not showing css is workin fine but some expandable menus not working

Please help me in this regard

### What is expected?

i want that theme should be work as it is in demo

### What is actually happening?

all case is defined in Steps to reproduce setion

### Additional data

i am using npm and all js that is defined in htlm file like dashboard and auth-login filt in tml folder

**Comment by PruthviPraj00** [comment]
Hello @mianmohsin188,

Rather than integrating React or Vue with HTML, we suggest using our [Sneat Vue Free](https://themeselection.com/item/sneat-free-vuetify-vuejs-admin-template/). While this free version doesn't have authentication integrated, it will be easier to add. Currently, there is no free version for React, but you can purchase the pro version [Sneat React Pro](https://themeselection.com/item/sneat-mui-react-nextjs-admin-template/). If you need any assistance, feel free to ask.

**Comment by PruthviPraj00** [comment]
Hello @mianmohsin188,

Thanks for getting in touch with us. 

Sorry, Integration and customization are not part of support. You can read all about the support policy here: https://themeforest.net/page/item_support_policy

Feel free to get in touch if you have any other queries.

**Comment by mianmohsin188** [comment]
Thank you for your response. I have managed to resolve this issue.

Thank you

**Comment by PruthviPraj00** [comment]
Hi @mianmohsin188 ,

Thank you for choosing our product/service. We hope that you had a positive experience with our team and found our product/support to be useful.

If you have a few moments to spare, we would greatly appreciate it if you could leave us a 5-star rating and a positive review. Your feedback would also help us to improve our product/support.

Writing a review is quick and easy! Just head over to this [article](https://help.themeselection.com/en/articles/7882853-how-can-i-provide-feedback-or-review-the-product) to learn how to share your feedback and experience with us.
Thank you for your time and support. We value your feedback and look forward to hearing from you soon.
Best regards
