### ISSUE TITLE
Laravel websocket not works with Sneat template

### ISSUE THREAD

**Issue by D0nVitalio** [themeselection/sneat-bootstrap-html-admin-template-free#35]
### Steps to reproduce

Hi! Have installed free version, then checked websocket is working in empty blade.
Then added @vite('resources/js/app.js') to head - not worked, then before </body> - again not worked. Thus when I add @vite('resources/js/app.js') - your dropdown on click on user icon not showing dropdown menu.

### What is expected?

Expect to receive message from websocket.

### What is actually happening?

no ws message comes

### Additional data

Code:
```
setTimeout( ()=>{
            window.Echo.private('my_private_channel.user.{{auth()->user()->id}}')
                .listen('.private_msg',(e)=>{
                console.log('checkWS p ', e);
            });
        },200);
```

**Comment by D0nVitalio** [comment]
Sorry) Had spell error in php. Now I can receive ws messages, but the dropdown on user icon still not works
![image](https://github.com/themeselection/sneat-bootstrap-html-admin-template-free/assets/22496972/553f2781-e9c7-4f55-99ef-dfb892c4fc9a)

Do you have ideas where I can fix this ↑ dropdown?

**Comment by smitbhalodiya** [comment]
Hi @D0nVitalio,

Thank you for reaching out to us.

You are trying to use Vite with our HTML template, but we would like to suggest that we have created a separate, free template specifically for Laravel that you can use. However, please note that this Laravel template is not integrated with Vite, but with **webpack.mix**, so you may need to customize it according to your needs. We may consider providing a version with Vite integration in future releases.
[Laravel Free Tamplate](https://github.com/themeselection/sneat-bootstrap-html-laravel-admin-template-free)

Let me know if you have any other queries.
