### ISSUE TITLE
Upgrade to Boostrap 5.3

### ISSUE THREAD

**Issue by tacman** [themeselection/sneat-bootstrap-html-admin-template-free#5]
Great theme, thanks for releasing it.

Bootstrap 5.2 is out, can you upgrade the library to use it?

I can submit a PR.

**Comment by monab** [comment]
Hi @tacman,

Thanks for using our theme and getting back to us. :)
Yes, bootstrap 5.2 is out already and we're planning to upgrade it with their CSS variables support.

We would love to integrate those all changes but it may take some time.
Let me know if you have any other queries :)
Stay Safe!!

**Comment by tacman** [comment]
do you think the theme will be updated to use the latest bootstrap?

**Comment by SHVM-09** [comment]
Hi [tacman](https://github.com/tacman),

Thank you for your patience!

We're pleased to inform you that the Sneat Free Template now comes with an update integrating Bootstrap 5.3.2. You can find detailed information in our [documentation](https://demos.themeselection.com/sneat-bootstrap-html-admin-template/documentation/). To get started, simply download the latest package from [here](https://themeselection.com/item/sneat-free-bootstrap-html-admin-template/).

This integration aims to address any concerns you may have had regarding the Bootstrap update in the template. If you have any additional questions or need further assistance, feel free to reach out.

Best Regards,

**Comment by tacman** [comment]
Thanks!

**Comment by SHVM-09** [comment]
Hi [tacman](https://github.com/tacman),

Thanks for your confirmation that the issue/query is resolved now, feel free to get back to us if you have any queries in future.

We are sure you loved our theme and support, please spend some time to rate & review us on ThemeSelection from your as per [here](https://help.themeselection.com/en/articles/7882853-how-can-i-provide-feedback-or-review-the-product). 

Your positive review motivates us to provide awesome updates with more features & top-notch customer support.

Cheers~
