### ISSUE TITLE
Bump Yarn Package

### ISSUE THREAD

**Issue by tacman** [themeselection/sneat-bootstrap-html-admin-template-free#7]
> Version: v1.0.0

## Feature Requirement

The yarn package is still at 1.0.0, can you bump it to the latest version please?

https://yarnpkg.com/package/sneat-bootstrap-html-admin-template-free

**Comment by monab** [comment]
Hi @tacman,

Thanks for using our theme and getting back to us. :)
We have used yarn package 1.0.0 for now.
We would love to update that, and we will be there with the updated version for the same soon.
Let me know if you have any other queries :)
Stay Safe!!
